name: Build APK
on: [push]
jobs:
  build:
    runs-on: ubuntu-22.04
    container:
      image: kivy/buildozer:latest
    steps:
    - uses: actions/checkout@v4

    - name: Fix dependencies
      run: |
        apt-get update -qq
        apt-get install -y gettext autopoint
        yes | sdkmanager "build-tools;33.0.2" "platforms;android-33" || true

    - name: Build APK
      env:
        BUILDOZER_WARN_ON_ROOT: 0
      run: buildozer android debug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: filetool-apk
        path: bin/*.apk
